---
- hosts: master
  vars_files:
  - env_variables 
  tasks:
  - name: Pulling images required for Kubernetes cluster
    shell: kubeadm config images pull

  - name: Restart services
    service:
      name: kubelet
      state: restarted

  - name: Initializing Kubernetes cluster
    become: true
    shell: "kubeadm init --apiserver-advertise-address {{ansible_eth0.ipv4.address}} --pod-network-cidr={{cidr_v}}"
    register: output
    ignore_errors: true

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}

  - name: Copying required files
    shell: "{{item}}"
    with_items:
      - "mkdir -p $HOME/.kube"
      - "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
      - "chown $(id -u):$(id -g) $HOME/.kube/config"

  - name: Install Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
