---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: staging
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer 
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  namespace: staging
spec:
  tls:
  - hosts:
    - staging-guestbook.mstakx.io
    secretName: <ingress-secret>
  rules:
  - host: staging-guestbook.mstakx.io
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend 
          servicePort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: production
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  namespace: production
spec:
  tls:
  - hosts:
    - staging-guestbook.mstakx.io
    secretName: <ingress-secret>
  rules:
  - host: guestbook.mstakx.io
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
