---
- hosts: all
  gather_facts: false
  vars_files:
   - env_variables 
  tasks:
   - name: Create Kubernetes repo
     file:
      path: /etc/yum.repos.d/kubernetes.repo
      state: touch

   - name: Add repo details in Kubernetes repo file.
     blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      block: |
       [kubernetes]
       name=Kubernetes
       baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
       enabled=1
       gpgcheck=0
       repo_gpgcheck=0
       gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
              https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

   - name: Install required packages
     yum:
      name: "{{ item }}"
      state: present
     with_items: "{{ packages }}"

   - name: Clear pending transactions
     command: yum-complete-transaction --cleanup-only

   - name: Start and enable services
     service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
     with_items: "{{ services }}"

   - name: Allow network ports
     firewalld:
      port: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
     with_items: "{{ ports }}"

   - name: Enable bridge firewall rule
     shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

